# Generated by Django 4.1.5 on 2023-06-08 07:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_person2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dprt_name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='person2',
            name='depr_name',
            field=models.ForeignKey(default = 1, on_delete=django.db.models.deletion.CASCADE, to='myApp.department'),
            preserve_default=False,
        ),
    ]
