# Generated by Django 4.1.5 on 2023-06-08 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_remove_person2_depr_name_delete_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dprt_name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='person2',
            name='depr_name',
            field=models.ForeignKey(default='00', on_delete=django.db.models.deletion.CASCADE, to='myApp.department'),
        ),
    ]
