# Generated by Django 4.1.5 on 2023-06-08 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_department_person2_depr_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person2',
            name='depr_name',
            field=models.ForeignKey(default='00', null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.department'),
        ),
    ]
