# Generated by Django 4.1.5 on 2023-06-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_alter_person2_depr_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_name', models.CharField(max_length=30)),
                ('class_name', models.CharField(max_length=30)),
                ('section_nmae', models.CharField(max_length=30)),
                ('monthly_fee', models.CharField(max_length=30)),
            ],
        ),
    ]
