# Generated by Django 4.1.5 on 2023-06-13 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_remove_person2_num_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='Fee_for_month',
        ),
        migrations.RemoveField(
            model_name='class',
            name='total_fee',
        ),
        migrations.AlterField(
            model_name='person2',
            name='depr_name',
            field=models.ForeignKey(default='00', null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.department'),
        ),
    ]
