# Generated by Django 4.1.5 on 2023-06-13 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_remove_class_fee_for_month_remove_class_total_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='Fee_for_month',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='class',
            name='total_fee',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='person2',
            name='num_name',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.class'),
        ),
        migrations.AlterField(
            model_name='person2',
            name='depr_name',
            field=models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.department'),
        ),
    ]
