# Generated by Django 4.1.5 on 2023-06-16 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0013_customers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class_name', models.CharField(max_length=30)),
                ('section_name', models.CharField(max_length=30)),
                ('total_amt', models.CharField(max_length=30)),
                ('scholarship', models.CharField(max_length=30)),
                ('special_disc', models.CharField(max_length=30)),
                ('final_amt', models.CharField(default='', max_length=30)),
                ('previous_dues', models.CharField(default='', max_length=30)),
                ('remaining_fee', models.CharField(default='', max_length=30)),
                ('fine_amt', models.CharField(default='', max_length=30)),
                ('paid_amt', models.CharField(default='', max_length=30)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
