# Generated by Django 4.1.5 on 2023-06-16 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_classes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='customer_name',
            new_name='student_name',
        ),
    ]
