# Generated by Django 4.1.5 on 2023-06-16 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0015_rename_customer_name_customers_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='Class_name',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.classes'),
        ),
    ]
