# Generated by Django 4.1.5 on 2023-06-16 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0016_customers_class_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='final_amt',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='fine_amt',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='paid_amt',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='previous_dues',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='remaining_fee',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='scholarship',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='special_disc',
        ),
        migrations.AddField(
            model_name='customers',
            name='final_amt',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='customers',
            name='fine_amt',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='customers',
            name='paid_amt',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='customers',
            name='previous_dues',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='customers',
            name='remaining_fee',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='customers',
            name='scholarship',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='customers',
            name='special_disc',
            field=models.CharField(default='', max_length=30),
        ),
    ]
