# Generated by Django 4.1.5 on 2023-06-16 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0017_remove_classes_final_amt_remove_classes_fine_amt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='fee_for_month',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='classes',
            name='monthly_fee',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='classes',
            name='total_installment',
            field=models.CharField(default='', max_length=30),
        ),
    ]
