# Generated by Django 4.1.5 on 2023-06-16 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0018_classes_fee_for_month_classes_monthly_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='customer_type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Partial', 'Partial')], max_length=30),
        ),
        migrations.AlterField(
            model_name='customers',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Disabled', 'Disabled')], max_length=30),
        ),
        migrations.CreateModel(
            name='Addbills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=30)),
                ('fine', models.CharField(max_length=30)),
                ('disc_amount', models.CharField(max_length=30)),
                ('paid_amount', models.CharField(max_length=30)),
                ('recived_by', models.CharField(max_length=30)),
                ('date', models.DateField(auto_now=True)),
                ('classs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.classes')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.customers')),
            ],
        ),
    ]
