# Generated by Django 4.1.5 on 2023-06-16 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0019_alter_customers_customer_type_alter_customers_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addbills',
            old_name='comment',
            new_name='Installment_amount',
        ),
        migrations.RenameField(
            model_name='addbills',
            old_name='disc_amount',
            new_name='Installment_name',
        ),
        migrations.RenameField(
            model_name='addbills',
            old_name='fine',
            new_name='months_from_to',
        ),
        migrations.RemoveField(
            model_name='addbills',
            name='classs',
        ),
        migrations.RemoveField(
            model_name='addbills',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='addbills',
            name='recived_by',
        ),
        migrations.RemoveField(
            model_name='addbills',
            name='student',
        ),
        migrations.AddField(
            model_name='addbills',
            name='Class',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.classes'),
        ),
    ]
