# Generated by Django 4.1.5 on 2023-06-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0020_rename_comment_addbills_installment_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=30)),
                ('class_name', models.CharField(max_length=30)),
                ('Installment_name', models.CharField(max_length=30)),
                ('paid_fee', models.CharField(default='0', max_length=30)),
                ('disc_amount', models.CharField(default='0', max_length=30)),
                ('remainng_amount', models.CharField(default='0', max_length=30)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
