# Generated by Django 4.1.5 on 2023-06-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0021_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='fee_amount',
            field=models.CharField(default='', max_length=30),
        ),
    ]
