# Generated by Django 4.2.2 on 2023-06-22 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0023_feestructure_invoice_student_payment_invoice_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='fee_structure',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='student',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='student',
        ),
        migrations.DeleteModel(
            name='FeeStructure',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
