# Generated by Django 4.2.2 on 2023-12-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0025_staff_student_attendancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='booleanvalue',
            field=models.BooleanField(default=False),
        ),
    ]
