# Generated by Django 4.2.2 on 2023-12-12 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0029_uploadedimage_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
    ]
